**矩阵简介**

In [ ]:
import numpy as np

A=np.array([(3,-1),(2,0)])
B=np.array([(-7,2),(3,5)])

# print(A+B)
# print(A-B)

**矩阵乘法**

In [ ]:
import numpy as np

# 必须要用矩阵，不能用array
A=np.matrix([(2,-3),(7,5)])
B=np.matrix([(10,-8),(12,-2)])

# print(A*B)

C=np.matrix([(1,2),(3,4)])
D=np.matrix([(5,6),(7,8)])

# 交换律不适用于矩阵乘法
# print(C*D)
# print(D*C)

E=np.matrix([(3,1,2),(-2,0,5)])
F=np.matrix([(-1,3),(0,5),(2,5)])

print(E*F)

print(F*E)

**矩阵的逆**

In [ ]:
import numpy as np
import numpy.matlib as mb

# 创建单位矩阵
I=mb.eye(2,2)

# print(I)

# 两种写法完全等价
# A=np.matrix([(2,-3),(7,5)])
# A=np.matrix('2,-3;7,5')
# print(A)

B=np.matrix('3,-4;2,-5')

B_1=np.linalg.inv(B)
print(B_1)

print(B_1*B)

**矩阵的逆（二）**

In [4]:
import numpy as np
import numpy.matlib as mb

A=np.matrix('1,0,1;0,2,1;1,1,1')

print(A)

# 矩阵的转置
A_1=A.T

print(A.I)

[[1 0 1]
 [0 2 1]
 [1 1 1]]
[[-1. -1.  2.]
 [-1.  0.  1.]
 [ 2.  1. -2.]]
